CC = g++

toss_a_coin.o:   
	g++ -c toss_a_coin $^

valley_of_plenty.o:   
	g++ -c valley_of_plenty $^

wolf.o:   
	g++ -c wolf $^

dandelion.o:   
	g++ -o /home/mezak/BioC2/Midterm2022/Straightforward $^

all: toss_a_coin.o valley_of_plenty.o wolf.o dandelion.o

clean: 
	 rm -f *.o
	 rm -f *.gch
